pipelines:
  - name: powershell_example
    steps:
      - name: simple_step
        type: PowerShell
        configuration:
          nodePool: win_2019
        execution:
          onExecute:
            - Write-Output "hello world!"
