pipelines:
  - name: windows_pipe
    steps:
      - name: test_ps_1
        type: PowerShell
        configuration:
          nodePool: win-static
          environmentVariables:
            foo: bar
        execution:
          onStart:
            - write-output "starting"
          onExecute:
            - write-output "hello world. executing..."
            - write-output "foo is $foo or is it $env:foo ?"
            - bad stuff
          onSuccess:
            - write-output "we did it!"
          onFailure:
            - write-output "we've failed"
          onComplete:
            - write-output "mission complete"
