resources:
  - name: myImage
    type: Image
    configuration:
      registry: tr_docker
      imageName: trriplejay/simpleserver
      imageTag: latest
      
  - name: myRepo
    type: GitRepo
    configuration:
      path: trriplejay/jfrog_samples
      gitProvider: tr_github
    
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art
      buildName: test
      buildNumber: 0
      
pipelines:
  - name: win_one_little_step
    steps:
      - name: test_envs
        type: PowerShell
        configuration:
          inputResources:
            - name: myImage
            - name: myRepo
            - name: myBuildInfo
          integrations:
            - name: johns_generic_envs
            - name: johns_art
        execution:
          onStart:
            - write-output "image resource path is $res_myImage_resourcePath"
            - write-output "current section. is it $current_script_section or $global:current_script_section"
          onExecute:
            - write-output "current section. is it $current_script_section or $global:current_script_section"
            - write-output "lets take a look at the whole ENV.. its faster..."
            - "dir env:"
          onSuccess:
            - write-output "current section. is it $current_script_section or $global:current_script_section"
          onFailure:
            - write-output "current section. is it $current_script_section or $global:current_script_section"
          onComplete:
            - write-output "current section. is it $current_script_section or $global:current_script_section"
            
  - name: windows_basic_pipe
    steps:
      - name: full_success
        type: PowerShell
        configuration:
          nodePool: win-static
          affinityGroup: winffinity
          environmentVariables:
            foo: bar
        execution:
          onStart:
            - write-output "starting"
          onExecute:
            - write-output "hello world. executing..."
            - write-output "foo is $foo or is it $env:foo ?"
          onSuccess:
            - write-output "we did it!"
          onFailure:
            - write-output "we've failed"
          onComplete:
            - write-output "mission complete"

      - name: fail_onExecute
        type: PowerShell
        configuration:
          inputSteps:
            - name: full_success
          nodePool: win-static
          environmentVariables:
            foo: bar
        execution:
          onStart:
            - write-output "starting"
          onExecute:
            - write-output "hello world. executing..."
            - write-output "foo is $foo or is it $env:foo ?"
            - bad stuff
          onSuccess:
            - write-output "we did it!"
          onFailure:
            - write-output "we've failed"
          onComplete:
            - write-output "mission complete"
            
      - name: fail_onStart
        type: PowerShell
        configuration:
          inputSteps:
            - name: full_success
          nodePool: win-static
          environmentVariables:
            foo: bar
        execution:
          onStart:
            - write-output "starting"
            - bad stuff
          onExecute:
            - write-output "hello world. executing..."
            - write-output "foo is $foo or is it $env:foo ?"
          onSuccess:
            - write-output "we did it!"
          onFailure:
            - write-output "we've failed"
          onComplete:
            - write-output "mission complete"

      - name: fail_onFailure
        type: PowerShell
        configuration:
          inputSteps:
            - name: full_success
          nodePool: win-static
          environmentVariables:
            foo: bar
        execution:
          onStart:
            - write-output "starting"
          onExecute:
            - write-output "hello world. executing..."
            - write-output "foo is $foo or is it $env:foo ?"
            - bad stuff
          onSuccess:
            - write-output "we did it!"
          onFailure:
            - write-output "we've failed"
            - bad stuff
          onComplete:
            - write-output "mission complete"

      - name: fail_onSuccess
        type: PowerShell
        configuration:
          affinityGroup: winffinity
          inputSteps:
            - name: full_success
          nodePool: win-static
          environmentVariables:
            foo: bar
        execution:
          onStart:
            - write-output "starting"
          onExecute:
            - write-output "hello world. executing..."
            - write-output "foo is $foo or is it $env:foo ?"
          onSuccess:
            - write-output "we did it!"
            - bad stuff
          onFailure:
            - write-output "we've failed"
          onComplete:
            - write-output "mission complete"

      - name: fail_onComplete
        type: PowerShell
        configuration:
          inputSteps:
            - name: full_success
          nodePool: win-static
          environmentVariables:
            foo: bar
        execution:
          onStart:
            - write-output "starting"
          onExecute:
            - write-output "hello world. executing..."
            - write-output "foo is $foo or is it $env:foo ?"
          onSuccess:
            - write-output "we did it!"
          onFailure:
            - write-output "we've failed"
          onComplete:
            - write-output "mission complete"
            - bad stuff
